version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "event-driven-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rp4kz81yf1l7"
s3_prefix = "event-driven-app"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

